# Generated by Django 6.0.5 on 2026-07-03 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_method_order_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
    ]
