# Generated by Django 6.0.5 on 2026-06-03 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('dress', 'Dresses'), ('ethnic', 'Ethnic Wear'), ('western', 'Western Wear'), ('traditional', 'Traditional'), ('casual', 'Casual Wear'), ('party', 'Party Wear'), ('office', 'Office Wear')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.IntegerField(default=0)),
                ('style', models.CharField(blank=True, choices=[('party', 'Party'), ('casual', 'Casual'), ('office', 'Office'), ('aesthetic', 'Aesthetic'), ('bohemian', 'Bohemian'), ('minimalist', 'Minimalist')], max_length=50, null=True)),
                ('collection', models.CharField(blank=True, choices=[('summer', 'Summer Collection'), ('winter', 'Winter Collection'), ('party', 'Party Edit'), ('workwear', 'Workwear Edit'), ('festive', 'Festive Collection'), ('latest', 'Latest Collection')], max_length=50, null=True)),
                ('size', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('stock', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('order_count', models.IntegerField(default=0)),
                ('wishlist_count', models.IntegerField(default=0)),
                ('avg_rating', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
