# Generated by Django 6.0.7 on 2026-07-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_category_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_best_seller',
            field=models.BooleanField(default=False, help_text='Check this to show product in Best Sellers section'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_new_arrival',
            field=models.BooleanField(default=False, help_text='Check this to show product in New Arrivals section'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_on_sale',
            field=models.BooleanField(default=False, help_text='Check this to show product in Sale section'),
        ),
        migrations.AlterField(
            model_name='product',
            name='style',
            field=models.CharField(blank=True, choices=[('party', 'Party'), ('casual', 'Casual'), ('office', 'Office'), ('aesthetic', 'Aesthetic')], max_length=50, null=True),
        ),
    ]
