# Generated by Django 6.0.5 on 2026-06-04 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
    ]
