# Generated by Django 6.0.5 on 2026-07-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_is_best_seller_product_is_new_arrival_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('collections', 'Collections'), ('casual', 'Casual Wear'), ('party', 'Party Wear'), ('office', 'Office Wear'), ('aesthetic', 'Aesthetic')], default='collections', max_length=50),
        ),
    ]
