# Generated by Django 6.0.5 on 2026-07-03 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category_is_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_hidden',
        ),
    ]
